# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'patientview' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # Pods for patientview
    pod 'SwiftyJSON', '4.0.0'
    pod 'Charts', '3.3.0'
    pod 'Firebase/Messaging', '~> 5.15.0'
    pod 'Firebase/Core', '~> 5.15.0'

end
